// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQWfhynYhenUWGRdCqpbVyfB4irwto1FQ',
    appId: '1:680294959147:web:d5d91d832911a59da2026e',
    messagingSenderId: '680294959147',
    projectId: 'chatapp-a1752',
    authDomain: 'chatapp-a1752.firebaseapp.com',
    storageBucket: 'chatapp-a1752.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSUrqVdIErOyjaXvDu1exAsqfKd4IjKWg',
    appId: '1:680294959147:android:04ab7e921c0fcda0a2026e',
    messagingSenderId: '680294959147',
    projectId: 'chatapp-a1752',
    storageBucket: 'chatapp-a1752.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBceUqmkN9Km7qPZF887_eSvP40CfiI9jo',
    appId: '1:680294959147:ios:6fc08319a0219a09a2026e',
    messagingSenderId: '680294959147',
    projectId: 'chatapp-a1752',
    storageBucket: 'chatapp-a1752.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBceUqmkN9Km7qPZF887_eSvP40CfiI9jo',
    appId: '1:680294959147:ios:6fc08319a0219a09a2026e',
    messagingSenderId: '680294959147',
    projectId: 'chatapp-a1752',
    storageBucket: 'chatapp-a1752.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQWfhynYhenUWGRdCqpbVyfB4irwto1FQ',
    appId: '1:680294959147:web:e5ec05c2967062d9a2026e',
    messagingSenderId: '680294959147',
    projectId: 'chatapp-a1752',
    authDomain: 'chatapp-a1752.firebaseapp.com',
    storageBucket: 'chatapp-a1752.appspot.com',
  );
}
